### ISSUE TITLE
getClickedInventory() is not a valid function of org.bukkit.event.inventory.InventoryClickEvent

### ISSUE THREAD

**Issue by electronicboy** [PapaHarni/McJobs#1]
Hello,

The plugin in it's current state doesn't compile;

getClickedInventory() is not a valid function of org.bukkit.event.inventory.InventoryClickEvent; I can only assume you meant to use something like getCurrentItem(); not 100% sure, however it's currently getting in the way of compilation (making the correct I've made as well as fixing the dependancies locally allowed it to compile, however not tested if it works, for all I know I have have over-looked something)

**Comment by PapaHarni** [comment]
Where you mean? I don't know what version of bukkit you use to compile. On Spigot 1.8.0 i can compile it without issue.

**Comment by PapaHarni** [comment]
Ok only where i found it  is in the Anvil.java , but this methode is not ready to use and will be not use on Compile, So you can delete the file Anvil.java if it an compilation error on you. I'm use NetBeansIDE 7,4 and it works to compile.

**Comment by electronicboy** [comment]
```
ant -f /Users/shane/work/src/McJobs -Dnb.internal.action.name=build jar
init:
deps-jar:
Created dir: /Users/shane/work/src/McJobs/build
Updating property file: /Users/shane/work/src/McJobs/build/built-jar.properties
Created dir: /Users/shane/work/src/McJobs/build/classes
Created dir: /Users/shane/work/src/McJobs/build/empty
Created dir: /Users/shane/work/src/McJobs/build/generated-sources/ap-source-output
Compiling 52 source files to /Users/shane/work/src/McJobs/build/classes
/Users/shane/work/src/McJobs/src/com/dmgkz/mcjobs/listeners/Anvil.java:53: error: cannot find symbol
        if(!(e.getClickedInventory() instanceof AnvilInventory))
  symbol:   method getClickedInventory()
  location: variable e of type InventoryClickEvent
/Users/shane/work/src/McJobs/src/com/dmgkz/mcjobs/listeners/Anvil.java:65: error: cannot find symbol
        AnvilInventory ai = (AnvilInventory)e.getClickedInventory();
  symbol:   method getClickedInventory()
  location: variable e of type InventoryClickEvent
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
/Users/shane/work/src/McJobs/nbproject/build-impl.xml:923: The following error occurred while executing this line:
/Users/shane/work/src/McJobs/nbproject/build-impl.xml:263: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 4 seconds)
```


netbeans 8.0.2 against git-Bukkit-0cf233d (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT) - Freshly compiled this morning

**Comment by electronicboy** [comment]
Oh, I see, Spigot only event, doesn't work when compiling directly against CraftBukkit.
